### ISSUE TITLE
Unique cluster name not implemented

### ISSUE THREAD

**Issue by gfortil** [Azure-Terraform/terraform-azurerm-kubernetes#84]
The random provider is used in this module, but the random generated number is not concatenated to the cluster_name variable.

```
cluster_name = (var.cluster_name != null ? var.cluster_name :
    "${var.names.resource_group_type}-${var.names.product_name}-${var.names.environment}-${var.names.location}")
```

**Comment by fabiendelpierre** [comment]
That's by design. Is there a reason why you can't generate a random string outside of the module and set it as part of your `cluster_name`? The example [here](https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/blob/master/examples/mixed-arch/main.tf) does it by setting a random string for the metadata's `product_name` but you could just as well pass a random string directly to this module via the `cluster_name` variable.

**Comment by gfortil** [comment]
I thought the point of having the default value is so that it can work out of the box. Having it this way only works for the first person who deploys in a given subscription until cluster_name is set by the user. You might as well require a user input for cluster_name.

**Comment by dutsmiller** [comment]
The random provider is NOT used in the module.  It's used in the example workspace so that the module can be tested by anyone.  The general consensus is that a single AKS cluster should work for each subscription as K8s tools can be used for isolation.  That said, the cluster_name variable exists for the rare cases where multiple cluster would be necessary.  In those cases, you'd just manually set the cluster_name for each cluster.
